<center
<# Experiment-2
# Using Pandas and Numpy 
</center>

<h1 style="text-align: center;">Experiment-2</h1>
<h1 style="text-align: center;">Using Pandas and Numpy </h1>

## Pandas
Pandas is a very popular library for working with data (its goal is to be the most powerful and flexible open-source tool). DataFrames are at the center of pandas. A DataFrame is structured like a table or spreadsheet. The rows and the columns both have indexes, and you can perform operations on rows or columns separately.

A pandas DataFrame can be easily changed and manipulated. Pandas has helpful functions for handling missing data, performing operations on columns and rows, and transforming data. If that wasn’t enough, a lot of SQL functions have counterparts in pandas, such as join, merge, filter by, and group by. With all of these powerful tools, it should come as no surprise that pandas is very popular among data scientists.

## NumPy
NumPy is an open-source Python library that facilitates efficient numerical operations on large quantities of data. There are a few functions that exist in NumPy that we use on pandas DataFrames. NumPy is a dependency of Pandas.

## NumPy Arrays
NumPy arrays are unique in that they are more flexible than normal Python lists. They are called ndarrays since they can have any number (n) of dimensions (d). They hold a collection of items of any one data type and can be either a vector (one-dimensional) or a matrix (multi-dimensional). NumPy arrays allow for fast element access and efficient data manipulation.

In [26]:
import numpy as np
list1 = [11,22,33,44]
array1 = np.array(list1)
print(array1)

[11 22 33 44]


In [28]:
# a two-dimensional ndarray from a list
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [29]:
# Slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [30]:
# Shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [31]:
# Join
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [32]:
# Sort
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


## Pandas Series and Dataframes
Just as the ndarray is the foundation of the NumPy library, the Series is the core object of the pandas library. A pandas Series is very similar to a one-dimensional NumPy array, but it has additional functionality that allows values in the Series to be indexed using labels. A NumPy array does not have the flexibility to do this. This labeling is useful when you are storing pieces of data that have other data associated with them. Say you want to store the ages of students in an online course to eventually figure out the average student age. If stored in a NumPy array, you could only access these ages with the internal ndarray indices 0,1,2.... With a Series object, the indices of values are set to 0,1,2... by default, but you can customize the indices to be other values such as student names so an age can be accessed using a name. Customized indices of a Series are established by sending values into the Series constructor, as you will see below.

A Series holds items of any one data type and can be created by sending in a scalar value, Python list, dictionary, or ndarray as a parameter to the pandas Series constructor. If a dictionary is sent in, the keys may be used as the indices.

In [17]:
# Creating a Series using a NumPy array of num with the default numerical indices
num = np.array([11,22,33])
series1 = pd.Series(num)
print(series1)

0    11
1    22
2    33
dtype: int32


In [11]:
import pandas as pd
import numpy as np
s=pd.Series(np.linspace(24,64,5))
print(s)

0    24.0
1    34.0
2    44.0
3    54.0
4    64.0
dtype: float64




When printing a Series, the data type of its elements is also printed. To customize the indices of a Series object, use the index argument of the Series constructor.

In [12]:
# Changing index of the series
import pandas as pd
import numpy as np
s1=pd.Series(range(1,15,3),index=[x for x in 'abcde'])
print(s1)

a     1
b     4
c     7
d    10
e    13
dtype: int64


In [13]:
# Various Operations on Series
import pandas as pd
import numpy as np
a=np.arange(9,13)
s2=pd.Series(index=a, data=a*2)
print(s2)
print()
print(s2[10])
print()
lst=[9,10,11,12]
s3=pd.Series(lst*2)
print(s3)

9     18
10    20
11    22
12    24
dtype: int32

20

0     9
1    10
2    11
3    12
4     9
5    10
6    11
7    12
dtype: int64


In [14]:
# Various functions of Series
import pandas as pd
Fruits=["Pen","Eraser","Scale","Book","Whitener","Colours"]
ser=pd.Series(Fruits, index=['p','e','s','b','w','c'])
print(ser)
print()
print("Index                :\t",ser.index)
print()
print("Values               :\t",ser.values)
print()
print("Data Type            :\t",ser.dtype)
print()
print("Shape                :\t",ser.shape)
print()
print("No. of bytes         :\t",ser.nbytes)
print()
print("No. of dimensions    :\t",ser.ndim)
print()
print("Size                 :\t",ser.size)
print()
print("Has NaNs?            :\t",ser.hasnans)
print()
print("Empty?               :\t",ser.empty)

p         Pen
e      Eraser
s       Scale
b        Book
w    Whitener
c     Colours
dtype: object

Index                :	 Index(['p', 'e', 's', 'b', 'w', 'c'], dtype='object')

Values               :	 ['Pen' 'Eraser' 'Scale' 'Book' 'Whitener' 'Colours']

Data Type            :	 object

Shape                :	 (6,)

No. of bytes         :	 48

No. of dimensions    :	 1

Size                 :	 6

Has NaNs?            :	 False

Empty?               :	 False


In [15]:
# Reindexing and dropping an element
import pandas as pd
ob2=pd.Series([1.50,12.75,24,35.25,46.50], index=['a','b','c','d','e'])
print(ob2)
print()
print(ob2.reindex(['b','e','c','a','d']))
print()
print(ob2.drop('c'))

a     1.50
b    12.75
c    24.00
d    35.25
e    46.50
dtype: float64

b    12.75
e    46.50
c    24.00
a     1.50
d    35.25
dtype: float64

a     1.50
b    12.75
d    35.25
e    46.50
dtype: float64


Another important type of object in the pandas library is the DataFrame. This object is similar in form to a matrix as it consists of rows and columns. Both rows and columns can be indexed with integers or String names. One DataFrame can contain many different types of data types, but within a column, everything has to be the same data type. A column of a DataFrame is essentially a Series. All columns must have the same number of elements (rows).

There are different ways to fill a DataFrame such as with a CSV file, a SQL query, a Python list, or a dictionary.

In [19]:
# Create a DataFrame
import pandas as pd
lis=[[25,45,60],[34,67,89],[88,90,56]]
df=pd.DataFrame(lis, index=['row1','row2','row3'], columns=['n1','n2','n3'])
print(df)

      n1  n2  n3
row1  25  45  60
row2  34  67  89
row3  88  90  56


In [20]:
# Using Dictionary
import pandas as pd
s1=pd.Series([1,2,3,4])
s2=pd.Series([5,6,7,8])
df1=pd.DataFrame({'AB':s1, 'CD':s2})
print(df1)

   AB  CD
0   1   5
1   2   6
2   3   7
3   4   8


In [22]:
# Various functions of DataFrame
import pandas as pd
d={'Hindi':{'Aditi':99,'Ayesha':90,'Anushka':94,'Neil':73,'Himanshi':60},
  'Maths':{'Aditi':100,'Ayesha':89,'Anushka':85,'Neil':83,'Himanshi':87},
  'English':{'Aditi':96,'Ayesha':100,'Anushka':55,'Neil':66,'Himanshi':65},
  'Science':{'Aditi':97,'Ayesha':77,'Anushka':89,'Neil':95,'Himanshi':98},
  'Computer':{'Aditi':100,'Ayesha':56,'Anushka':95,'Neil':99,'Himanshi':78},}
prd=pd.DataFrame(d)
print(prd)
print()
print("Index    :\t",prd.index)
print("Columns  :\t",prd.columns)
print("Axes:")
print(prd.axes)
print()
print("Data Type:")
print(prd.dtypes)
print()
print("No. of rows  :\t",len(prd))
print()
print("Count(rows):")
print(prd.count())
print()
print("Count(columns):")
print(prd.count(axis=1))
print()
print("Shape        :\t",prd.shape)
print()
print("Values:")
print(prd.values)
print()
print("No. of dimensions    :\t",prd.ndim)
print("Size                 :\t",prd.size)
print("Empty?               :\t",prd.empty)
print()
print("Transpose:")
print(prd.T)

          Hindi  Maths  English  Science  Computer
Aditi        99    100       96       97       100
Ayesha       90     89      100       77        56
Anushka      94     85       55       89        95
Neil         73     83       66       95        99
Himanshi     60     87       65       98        78

Index    :	 Index(['Aditi', 'Ayesha', 'Anushka', 'Neil', 'Himanshi'], dtype='object')
Columns  :	 Index(['Hindi', 'Maths', 'English', 'Science', 'Computer'], dtype='object')
Axes:
[Index(['Aditi', 'Ayesha', 'Anushka', 'Neil', 'Himanshi'], dtype='object'), Index(['Hindi', 'Maths', 'English', 'Science', 'Computer'], dtype='object')]

Data Type:
Hindi       int64
Maths       int64
English     int64
Science     int64
Computer    int64
dtype: object

No. of rows  :	 5

Count(rows):
Hindi       5
Maths       5
English     5
Science     5
Computer    5
dtype: int64

Count(columns):
Aditi       5
Ayesha      5
Anushka     5
Neil        5
Himanshi    5
dtype: int64

Shape        :	 (5, 5)

Val

In [38]:
import pandas as pd
dt={'Population':[10927986,12691836,4631392,4328063],
   'Hospitals':[189,208,149,157],
   'Schools':[7916,8508,7226,7617]}
dtf5=pd.DataFrame(dt, index=['Delhi','Mumbai','Kolkata','Chennai'])
print(dtf5)
print()
print(dtf5['Population'])
print()
print(dtf5.Schools)
print()
print(dtf5[['Population','Hospitals']])
print()
print(dtf5.loc['Mumbai':'Kolkata',:])
print()
print(dtf5.loc[:,'Population':'Hospitals'])
print()
print(dtf5.loc['Mumbai':'Kolkata','Population':'Hospitals'])
print()
print(dtf5.iloc[0:3,2:])
print()
print(dtf5.Population['Mumbai'])
print()
print(dtf5.at['Chennai','Schools'])
print()
print(dtf5.iat[2,2])
print()
dtf5['Density']=[1500,1219,1630,1050]
print(dtf5)
print()
print(dtf5.assign(NewColumn=[245,2345,34,436]))
print()
dtf5.loc['Bengaluru'] = [2355413, 344, 3455, 39]
print(dtf5)
print()
del dtf5['Density']
print(dtf5)
print()
dtf5 = dtf5.drop(['Bengaluru'])
print(dtf5)

         Population  Hospitals  Schools
Delhi      10927986        189     7916
Mumbai     12691836        208     8508
Kolkata     4631392        149     7226
Chennai     4328063        157     7617

Delhi      10927986
Mumbai     12691836
Kolkata     4631392
Chennai     4328063
Name: Population, dtype: int64

Delhi      7916
Mumbai     8508
Kolkata    7226
Chennai    7617
Name: Schools, dtype: int64

         Population  Hospitals
Delhi      10927986        189
Mumbai     12691836        208
Kolkata     4631392        149
Chennai     4328063        157

         Population  Hospitals  Schools
Mumbai     12691836        208     8508
Kolkata     4631392        149     7226

         Population  Hospitals
Delhi      10927986        189
Mumbai     12691836        208
Kolkata     4631392        149
Chennai     4328063        157

         Population  Hospitals
Mumbai     12691836        208
Kolkata     4631392        149

         Schools
Delhi       7916
Mumbai      8508
Kolkata     7226

In [24]:
import pandas as pd
Days=['Monday','Tuesday','Wednesday','Thursday','Friday']
Classes=[6,0,3,0,8]
dc={'Days':Days,'No. of Classes':Classes}
classdf=pd.DataFrame(dc, index=[True,False,True,False,True])
print(classdf)
print()
print(classdf.loc[True])

            Days  No. of Classes
True      Monday               6
False    Tuesday               0
True   Wednesday               3
False   Thursday               0
True      Friday               8

           Days  No. of Classes
True     Monday               6
True  Wednesday               3
True     Friday               8
